name:                pine
version:             0.1.0.0
github:              "totbwf/pine"
license:             MIT
author:              "Reed Mullanix"
maintainer:          "reedmullanix@gmail.com"
copyright:           "2018 Reed Mullanix"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on Github at <https://github.com/githubuser/pixy-lang#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 6 && < 7
- mtl >= 2 && < 3
- text >= 1 && < 2
- containers >= 0.5 && < 0.6
- pretty >= 1.1 && < 1.2
- repline >= 0.1 && < 0.2

executables:
  pine:
    main:                Pine/Main.hs
    source-dirs:         src
    default-extensions:
    - TupleSections
    - OverloadedStrings
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N

# tests:
#   pixy-lang-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N

